### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by clienthax** [IzzelAliz/AmberShop#34]
Version: AmberShop-1.1.5-all.jar
I am guessing this may be related to me removing a mod (littletiles), but it only seems to of appeared now, and can likely be handled much cleaner.
[ambershop.mv.zip](https://github.com/EpicBanItemTeam/AmberShop/files/4568064/ambershop.mv.zip)

```> [16:51:18] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task ambershop-S-53 owned by Plugin{id=ambershop, name=AmberShop, version=1.1.5, description=A trading plugin., url=https://github.com/IzzelAliz/AmberShop, authors=[IzzelAliz], source=/home/container/./mods/plugins/AmberShop-1.1.5-all.jar}, but an error occured.
java.util.concurrent.ExecutionException: org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize something correctly, likely due to bad type data.
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_242]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_242]
at io.izzel.ambershop.listener.DisplayListener$PlayerChunkChangeTask.accept(DisplayListener.java:165) ~[DisplayListener$PlayerChunkChangeTask.class:?]
at io.izzel.ambershop.listener.DisplayListener$PlayerChunkChangeTask.accept(DisplayListener.java:128) ~[DisplayListener$PlayerChunkChangeTask.class:?]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:74) ~[SyncScheduler.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:188) ~[SchedulerBase.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:174) ~[SchedulerBase.class:1.12.2-2838-7.2.1-RC4017]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_242]
at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:112) [SchedulerBase.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:47) [SyncScheduler.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:189) [SpongeScheduler.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:457) [SpongeMod.class:1.12.2-2838-7.2.1-RC4017]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_496_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:703) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:657) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize something correctly, likely due to bad type data.
at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:89) ~[AbstractDataBuilder.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.data.SpongeDataManager.lambda$deserialize$1(SpongeDataManager.java:196) ~[SpongeDataManager.class:1.12.2-2838-7.2.1-RC4017]
at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_242]
at org.spongepowered.common.data.SpongeDataManager.deserialize(SpongeDataManager.java:196) ~[SpongeDataManager.class:1.12.2-2838-7.2.1-RC4017]
at io.izzel.ambershop.data.ShopRecord.readMeta(ShopRecord.java:104) ~[ShopRecord.class:?]
at io.izzel.ambershop.data.ShopRecord.readResultSet(ShopRecord.java:140) ~[ShopRecord.class:?]
at io.izzel.ambershop.data.ShopDataSourceImpl.lambda$getByChunk$11(ShopDataSourceImpl.java:211) ~[ShopDataSourceImpl.class:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
... 1 more
Caused by: java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_242]
at org.spongepowered.common.data.builder.item.SpongeItemStackSnapshotBuilder.buildContent(SpongeItemStackSnapshotBuilder.java:61) ~[SpongeItemStackSnapshotBuilder.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87) ~[AbstractDataBuilder.class:1.12.2-2838-7.2.1-RC4017]
at org.spongepowered.common.data.SpongeDataManager.lambda$deserialize$1(SpongeDataManager.java:196) ~[SpongeDataManager.class:1.12.2-2838-7.2.1-RC4017]
at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_242]
at org.spongepowered.common.data.SpongeDataManager.deserialize(SpongeDataManager.java:196) ~[SpongeDataManager.class:1.12.2-2838-7.2.1-RC4017]
at io.izzel.ambershop.data.ShopRecord.readMeta(ShopRecord.java:104) ~[ShopRecord.class:?]
at io.izzel.ambershop.data.ShopRecord.readResultSet(ShopRecord.java:140) ~[ShopRecord.class:?]
at io.izzel.ambershop.data.ShopDataSourceImpl.lambda$getByChunk$11(ShopDataSourceImpl.java:211) ~[ShopDataSourceImpl.class:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_242]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_242]
... 1 more```

**Comment by IzzelAliz** [comment]
Try to use `/as fix`

**Comment by clienthax** [comment]
```
> as fix=> [13:01:02] [Server thread/INFO] [nucleus]: Server ran the command: /as fix
[13:01:02] [pool-10-thread-2/INFO] [minecraft/DedicatedServer]: Deleted 2 corrpted shop records, ID: 401 1159
```

Seems to of done something
